# a_tensor_initialization.py

In [1]:
import torch

In [2]:
# torch.Tensor class
t1 = torch.Tensor([1, 2, 3], device='cpu')
print(t1.dtype)   # >>> torch.float32
print(t1.device)  # >>> cpu
print(t1.requires_grad)  # >>> False
print(t1.size())  # torch.Size([3])
print(t1.shape)   # torch.Size([3])

# if you have gpu device
# t1_cuda = t1.to(torch.device('cuda'))
# or you can use shorthand
# t1_cuda = t1.cuda()
t1_cpu = t1.cpu()

torch.float32
cpu
False
torch.Size([3])
torch.Size([3])


In [3]:
t2 = torch.tensor([1, 2, 3], device='cpu')
print(t2.dtype)  # 데이터 타입: torch.int64
print(t2.device)  # 디바이스: cpu
print(t2.requires_grad)  # 미분 활성화 여부: False
print(t2.size())  # 크기: torch.Size([3])
print(t2.shape)  # 모양: torch.Size([3])

# GPU가 있을 경우, 텐서를 CUDA 디바이스로 전송하는 코드
# t2_cuda = t2.to(torch.device('cuda'))
# t2_cuda = t2.cuda()

# CPU로 변환
t2_cpu = t2.cpu()

torch.int64
cpu
False
torch.Size([3])
torch.Size([3])


In [4]:
# 1차원 텐서 (벡터)
a2 = torch.tensor([1])  # 크기: torch.Size([1]), 차원: 1
print(a2.shape, a2.ndim)

# 1차원 텐서 (5개의 원소를 가진 벡터)
a3 = torch.tensor([1, 2, 3, 4, 5])  # 크기: torch.Size([5]), 차원: 1
print(a3.shape, a3.ndim)

# 2차원 텐서 (5x1)
a4 = torch.tensor([[1], [2], [3], [4], [5]])  # 크기: torch.Size([5, 1]), 차원: 2
print(a4.shape, a4.ndim)

# 2차원 텐서 (3x2)
a5 = torch.tensor([  # 크기: torch.Size([3, 2]), 차원: 2
    [1, 2],
    [3, 4],
    [5, 6]
])
print(a5.shape, a5.ndim)

# 3차원 텐서 (3x2x1)
a6 = torch.tensor([  # 크기: torch.Size([3, 2, 1]), 차원: 3
    [[1], [2]],
    [[3], [4]],
    [[5], [6]]
])
print(a6.shape, a6.ndim)

#4차원 텐서 (3x1x2x1)
a7 = torch.tensor([  # 크기: torch.Size([3, 1, 2, 1]), 차원: 4
    [[[1], [2]]],
    [[[3], [4]]],
    [[[5], [6]]]
])
print(a7.shape, a7.ndim)

# 4차원 텐서 (3x1x2x3)
a8 = torch.tensor([  # 크기: torch.Size([3, 1, 2, 3]), 차원: 4
    [[[1, 2, 3], [2, 3, 4]]],
    [[[3, 1, 1], [4, 4, 5]]],
    [[[5, 6, 2], [6, 3, 1]]]
])
print(a8.shape, a8.ndim)

# 5차원 텐서 (3x1x2x3x1)
a9 = torch.tensor([  # 크기: torch.Size([3, 1, 2, 3, 1]), 차원: 5
    [[[[1], [2], [3]], [[2], [3], [4]]]],
    [[[[3], [1], [1]], [[4], [4], [5]]]],
    [[[[5], [6], [2]], [[6], [3], [1]]]]
])
print(a9.shape, a9.ndim)

# 2차원 텐서 (4x5)
a10 = torch.tensor([  # 크기: torch.Size([4, 5]), 차원: 2
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
])
print(a10.shape, a10.ndim)

# 3차원 텐서 (4x1x5)
a10 = torch.tensor([  # 크기: torch.Size([4, 1, 5]), 차원: 3
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
])
print(a10.shape, a10.ndim)

# 마지막 텐서는 각 3차원 텐서의 길이가 맞지 않아 ValueError를 발생시킵니다.
a11 = torch.tensor([                 # ValueError: expected sequence of length 3 at dim 3 (got 2)
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
])

torch.Size([1]) 1
torch.Size([5]) 1
torch.Size([5, 1]) 2
torch.Size([3, 2]) 2
torch.Size([3, 2, 1]) 3
torch.Size([3, 1, 2, 1]) 4
torch.Size([3, 1, 2, 3]) 4
torch.Size([3, 1, 2, 3, 1]) 5
torch.Size([4, 5]) 2
torch.Size([4, 1, 5]) 3


ValueError: expected sequence of length 3 at dim 3 (got 2)

텐서를 생성하는 다양한 방법을 소개하며, 각 방법의 데이터 타입, 장치, 크기 등을 확인할 수 있다.
torch.Tensor와 torch.tensor의 차이점에 유의해야 하며, torch.as_tensor는 리스트나 배열을 참조하여 생성한다.
GPU 장치에서의 텐서 생성 및 변환 과정도 함께 다루고 있다.

# b_tensor_initialization_copy.py

In [5]:
import torch
import numpy as np

In [6]:
# 리스트를 이용한 텐서 생성
l1 = [1, 2, 3]
t1 = torch.Tensor(l1)

l2 = [1, 2, 3]
t2 = torch.tensor(l2)

l3 = [1, 2, 3]
t3 = torch.as_tensor(l3) # 참조

# 리스트의 첫 번째 값 변경
l1[0] = 100
l2[0] = 100
l3[0] = 100

# 텐서 출력
print(t1)  # Tensor([1., 2., 3.])
print(t2)  # Tensor([1, 2, 3])
print(t3)  # Tensor([100, 2, 3]) -> 리스트 l3의 참조

tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([1, 2, 3])


In [7]:
# NumPy 배열을 이용한 텐서 생성
l4 = np.array([1, 2, 3])
t4 = torch.Tensor(l4)

l5 = np.array([1, 2, 3])
t5 = torch.tensor(l5)

l6 = np.array([1, 2, 3])
t6 = torch.as_tensor(l6) # 참조

# NumPy 배열의 첫 번째 값 변경
l4[0] = 100
l5[0] = 100
l6[0] = 100

# 텐서 출력b
print(t4)  # Tensor([1., 2., 3.])
print(t5)  # Tensor([1, 2, 3])
print(t6)  # Tensor([100, 2, 3]) -> NumPy 배열 l6의 참조

tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([100,   2,   3])


리스트와 NumPy 배열을 사용하여 텐서를 생성할 때의 차이를 설명한다.
특히 torch.as_tensor를 사용하면 원본 데이터에 대한 참조가 생성되어, 원본 데이터 변경 시 텐서도 영향을 받게 된다.
이러한 특성을 이해하는 것이 메모리 관리 및 데이터 일관성 유지에 중요하다.

# c_tensor_initialization_constant_values.py

In [8]:
import torch

# 5개의 1로 채워진 텐서 생성
t1 = torch.ones(size=(5,))  # or torch.ones(5)
t1_like = torch.ones_like(input=t1)
print(t1)       
print(t1_like)  

# 6개의 0으로 채워진 텐서 생성
t2 = torch.zeros(size=(6,))  # or torch.zeros(6)
t2_like = torch.zeros_like(input=t2)
print(t2)       
print(t2_like)  

# 4개의 초기화되지 않은 텐서 생성
t3 = torch.empty(size=(4,))  # or torch.empty(4)
t3_like = torch.empty_like(input=t3)
print(t3)       # 초기화되지 않은 불규칙한 값
print(t3_like)  # 초기화되지 않은 불규칙한 값

# 3x3 단위 행렬 생성
t4 = torch.eye(n=3)
print(t4)  

tensor([1., 1., 1., 1., 1.])
tensor([1., 1., 1., 1., 1.])
tensor([0., 0., 0., 0., 0., 0.])
tensor([0., 0., 0., 0., 0., 0.])
tensor([0., 0., 0., 0.])
tensor([0., 0., 0., 0.])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


상수로 채워진 텐서를 생성하는 방법을 소개하며, torch.ones, torch.zeros, torch.empty의 용도와 초기화 상태를 비교한다.
단위 행렬을 생성하는 torch.eye 함수도 사용되며, 다양한 초기화 방법의 선택이 학습 모델 성능에 미치는 영향을 이해하는 데 도움이 된다.

# d_tensor_initialization_random_values.py

In [9]:
# 10부터 20 사이의 정수를 가지는 랜덤 텐서 생성
t1 = torch.randint(low=10, high=20, size=(1, 2))
print(t1)  # >>> tensor([[x, y]])  # x, y는 10~19 사이의 정수

# 0과 1 사이의 실수를 가지는 랜덤 텐서 생성
t2 = torch.rand(size=(1, 3))
print(t2) 

# 평균 0, 표준편차 1인 정규 분포에서 랜덤한 실수를 가지는 텐서 생성
t3 = torch.randn(size=(1, 3))
print(t3)  

# 평균 10, 표준편차 1인 정규 분포에서 랜덤한 실수를 가지는 텐서 생성
t4 = torch.normal(mean=10.0, std=1.0, size=(3, 2))
print(t4) 

# 0부터 5까지 균등한 간격으로 3개의 값을 생성
t5 = torch.linspace(start=0.0, end=5.0, steps=3)
print(t5)  # >>> tensor([0.0000, 2.5000, 5.0000])

# 0부터 4까지 1씩 증가하는 정수로 텐서를 생성
t6 = torch.arange(5)
print(t6)  # >>> tensor([0, 1, 2, 3, 4])

tensor([[11, 11]])
tensor([[0.4900, 0.9904, 0.7808]])
tensor([[-1.2219,  0.0555,  0.1962]])
tensor([[ 9.2344,  9.8247],
        [ 9.1812,  9.7243],
        [10.2509,  9.4246]])
tensor([0.0000, 2.5000, 5.0000])
tensor([0, 1, 2, 3, 4])


In [10]:
# 시드를 설정한 후 랜덤 텐서 생성
torch.manual_seed(1729)
random1 = torch.rand(2, 3)
print(random1) 

random2 = torch.rand(2, 3)
print(random2) 

print()

# 같은 시드를 설정하면 동일한 난수 시퀀스를 재현 가능
torch.manual_seed(1729)
random3 = torch.rand(2, 3)
print(random3)  # random1과 동일한 결과

random4 = torch.rand(2, 3)
print(random4)  # random2와 동일한 결과

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


랜덤 텐서를 생성하는 다양한 방법을 다룬다. 각 텐서 생성 함수의 용도와 그에 따른 값의 분포를 설명한다.
랜덤 시드를 설정하는 과정은 실험의 재현성을 보장하기 위해 필수적이다.
특히, torch.randint, torch.rand, torch.randn 등을 활용하여 난수 생성의 다양성을 확인할 수 있다.

# e_tensor_type_conversion.py

In [11]:
# 기본 float32 타입으로 ones 텐서 생성
a = torch.ones((2, 3))
print(a.dtype)  # >>> torch.float32

# int16 타입으로 ones 텐서 생성
b = torch.ones((2, 3), dtype=torch.int16)
print(b)  # >>> tensor([[1, 1, 1], [1, 1, 1]], dtype=torch.int16)

# float64 타입으로 0과 1 사이의 랜덤 값을 생성하고, 20을 곱해 범위를 확장
c = torch.rand((2, 3), dtype=torch.float64) * 20.0
print(c)  # >>> 예시: tensor([[12.5, 19.4, 2.3], [6.8, 17.9, 4.5]], dtype=torch.float64)

# b 텐서를 int32 타입으로 변환
d = b.to(torch.int32)
print(d)  # >>> tensor([[1, 1, 1], [1, 1, 1]], dtype=torch.int32)


torch.float32
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
tensor([[18.0429,  7.2532, 19.6519],
        [10.8626,  2.1505, 19.6913]], dtype=torch.float64)
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)


In [12]:
# double 타입의 텐서 생성
double_d = torch.ones(10, 2, dtype=torch.double)
# short 타입의 텐서 생성
short_e = torch.tensor([[1, 2]], dtype=torch.short)

# zeros로 double 타입 텐서 생성
double_d = torch.zeros(10, 2).double()
# ones로 short 타입 텐서 생성
short_e = torch.ones(10, 2).short()

# to()를 사용한 데이터 타입 변환
double_d = torch.zeros(10, 2).to(torch.double)
short_e = torch.ones(10, 2).to(dtype=torch.short)

# type()을 사용한 데이터 타입 변환
double_d = torch.zeros(10, 2).type(torch.double)
short_e = torch.ones(10, 2).type(dtype=torch.short)

# dtype 출력
print(double_d.dtype)  # >>> torch.float64
print(short_e.dtype)   # >>> torch.int16

torch.float64
torch.int16


In [13]:
# double 타입의 텐서 생성
double_f = torch.rand(5, dtype=torch.double)
# short 타입으로 변환
short_g = double_f.to(torch.short)
# double_f와 short_g의 곱의 결과의 데이터 타입 확인
print((double_f * short_g).dtype)  # >>> torch.float64

torch.float64


텐서의 데이터 타입을 변환하는 방법을 설명한다. 데이터 타입에 따른 메모리 사용량 및 연산 성능 차이를 인식하는 것이 중요하다.
type()과 to() 메소드를 통해 다양한 데이터 타입을 설정하는 방식이 구체적으로 다뤄진다.
변환 후의 텐서에서 연산 결과의 데이터 타입도 확인하여 타입 변환의 효과를 이해할 수 있다.

# f_tensor_operations.py

In [14]:
# 텐서 더하기
t1 = torch.ones(size=(2, 3))
t2 = torch.ones(size=(2, 3))
t3 = torch.add(t1, t2)
t4 = t1 + t2
print(t3)
print(t4)

tensor([[2., 2., 2.],
        [2., 2., 2.]])
tensor([[2., 2., 2.],
        [2., 2., 2.]])


In [15]:
# 텐서 빼기
t5 = torch.sub(t1, t2)
t6 = t1 - t2
print(t5)
print(t6)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [16]:
# 텐서 곱하기
t7 = torch.mul(t1, t2)
t8 = t1 * t2
print(t7)
print(t8)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [17]:
# 텐서 나누기
t9 = torch.div(t1, t2)
t10 = t1 / t2
print(t9)
print(t10)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


텐서 간의 기본적인 산술 연산을 소개하며, 연산의 결과를 통해 텐서의 조작 방식과 그 의미를 이해할 수 있다.
더하기, 빼기, 곱하기, 나누기 연산을 각각 명시적으로 호출하는 방법과 연산자를 통한 간결한 표현을 모두 보여준다.
텐서 연산의 메커니즘을 이해하는 것은 신경망의 기본 구조와 동작을 이해하는 데 중요하다.

# g_tensor_operations_mm.py

In [18]:
# 벡터의 내적
t1 = torch.dot(
    torch.tensor([2, 3]), torch.tensor([2, 1])
)
print(t1, t1.size())  # 내적 결과와 크기

# 행렬의 곱
t2 = torch.randn(2, 3)
t3 = torch.randn(3, 2)
t4 = torch.mm(t2, t3)
print(t4, t4.size())  # 행렬 곱 결과와 크기

# 배치 행렬 곱
t5 = torch.randn(10, 3, 4)
t6 = torch.randn(10, 4, 5)
t7 = torch.bmm(t5, t6)
print(t7.size())  # 배치 행렬 곱 결과의 크기

tensor(7) torch.Size([])
tensor([[1.6750, 2.2840],
        [0.0956, 1.0294]]) torch.Size([2, 2])
torch.Size([10, 3, 5])


내적과 행렬 곱의 개념을 다루며, 벡터와 행렬 간의 연산을 통한 차원 변환을 명확하게 보여준다.
torch.dot과 torch.mm을 활용하여 내적 및 행렬 곱을 수행하는 방법을 제시하며, 배치 행렬 곱을 통한 다차원 텐서 연산의 개념도 소개된다.
이 과정에서 텐서의 차원에 따른 연산 결과의 크기를 파악하는 것이 중요하다.

# h_tensor_operations_matmul.py

In [19]:
# vector x vector: dot product  # 벡터 x 벡터: 내적
t1 = torch.randn(3)
t2 = torch.randn(3)
print(torch.matmul(t1, t2).size())  # torch.Size([])  # 벡터 간의 내적 결과는 스칼라

# matrix x vector: broadcasted dot  # 행렬 x 벡터: 브로드캐스트 내적
t3 = torch.randn(3, 4)
t4 = torch.randn(4)
print(torch.matmul(t3, t4).size())  # torch.Size([3])  # 행렬과 벡터의 곱 결과는 벡터

# batched matrix x vector: broadcasted dot  # 배치된 행렬 x 벡터: 브로드캐스트 내적
t5 = torch.randn(10, 3, 4)
t6 = torch.randn(4)
print(torch.matmul(t5, t6).size())  # torch.Size([10, 3])  # 배치된 행렬과 벡터의 곱 결과는 배치된 벡터

# batched matrix x batched matrix: bmm  # 배치된 행렬 x 배치된 행렬: 배치 행렬 곱
t7 = torch.randn(10, 3, 4)
t8 = torch.randn(10, 4, 5)
print(torch.matmul(t7, t8).size())  # torch.Size([10, 3, 5])  # 배치된 행렬 간의 곱 결과는 배치된 행렬

# batched matrix x matrix: bmm  # 배치된 행렬 x 일반 행렬: 배치 행렬 곱
t9 = torch.randn(10, 3, 4)
t10 = torch.randn(4, 5)
print(torch.matmul(t9, t10).size())  # torch.Size([10, 3, 5])  # 배치된 행렬과 일반 행렬의 곱 결과는 배치된 행렬

torch.Size([])
torch.Size([3])
torch.Size([10, 3])
torch.Size([10, 3, 5])
torch.Size([10, 3, 5])


torch.matmul을 사용하여 다양한 형태의 텐서 곱을 수행한다. 
벡터와 행렬, 배치된 텐서 간의 곱의 결과 차원을 보여주며, 브로드캐스팅 개념을 활용한 연산을 강조한다.
다양한 곱셈 방식을 이해하는 것은 복잡한 신경망 아키텍처에서의 텐서 흐름을 관리하는 데 필수적이다.

# i_tensor_broadcasting.py

In [46]:
t1 = torch.tensor([1.0, 2.0, 3.0])
t2 = 2.0
print(t1 * t2)  # t1에 2.0을 곱함


tensor([2., 4., 6.])


In [47]:
t3 = torch.tensor([[0, 1], [2, 4], [10, 10]])
t4 = torch.tensor([4, 5])
print(t3 - t4)  # t3에서 t4를 빼기


tensor([[-4, -4],
        [-2, -1],
        [ 6,  5]])


In [48]:
t5 = torch.tensor([[1., 2.], [3., 4.]])
print(t5 + 2.0)  # t5에 2.0을 더함
print(t5 - 2.0)  # t5에서 2.0을 뺌
print(t5 * 2.0)  # t5에 2.0을 곱함
print(t5 / 2.0)  # t5를 2.0으로 나눔


tensor([[3., 4.],
        [5., 6.]])
tensor([[-1.,  0.],
        [ 1.,  2.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])


In [49]:
def normalize(x):
  return x / 255  # 입력 텐서를 255로 나누어 정규화

t6 = torch.randn(3, 28, 28)
print(normalize(t6).size())  # 정규화된 텐서의 크기 출력

torch.Size([3, 28, 28])


In [50]:
t7 = torch.tensor([[1, 2], [0, 3]])  # torch.Size([2, 2])
t8 = torch.tensor([[3, 1]])  # torch.Size([1, 2])
t9 = torch.tensor([[5], [2]])  # torch.Size([2, 1])
t10 = torch.tensor([7])  # torch.Size([1])
print(t7 + t8)
print(t7 + t9) 
print(t8 + t9)   
print(t7 + t10)

tensor([[4, 3],
        [3, 4]])
tensor([[6, 7],
        [2, 5]])
tensor([[8, 6],
        [5, 3]])
tensor([[ 8,  9],
        [ 7, 10]])


In [51]:
t11 = torch.ones(4, 3, 2)
t12 = t11 * torch.rand(3, 2)  # 3차원과 2차원 텐서 간의 브로드캐스팅
print(t12.shape)  # 결과 텐서의 크기 출력

t13 = torch.ones(4, 3, 2)
t14 = t13 * torch.rand(3, 1)  # 3차원 텐서에 1차원 텐서 브로드캐스팅
print(t14.shape)  # 결과 텐서의 크기 출력

t15 = torch.ones(4, 3, 2)
t16 = t15 * torch.rand(1, 2)  # 1차원 텐서 브로드캐스팅
print(t16.shape)  # 결과 텐서의 크기 출력

t17 = torch.ones(5, 3, 4, 1)
t18 = torch.rand(3, 1, 1)  # 3차원과 1차원 텐서 간의 브로드캐스팅
print((t17 + t18).size())  # 결과 텐서의 크기 출력

# 곱해도 더해도 크기는 변하지 않는다.

torch.Size([4, 3, 2])
torch.Size([4, 3, 2])
torch.Size([4, 3, 2])
torch.Size([5, 3, 4, 1])


In [26]:
t19 = torch.empty(5, 1, 4, 1)
t20 = torch.empty(3, 1, 1)
print((t19 + t20).size())  # torch.Size([5, 3, 4, 1])  # 브로드캐스팅된 결과 크기 출력

t21 = torch.empty(1)
t22 = torch.empty(3, 1, 7)
print((t21 + t22).size())  # torch.Size([3, 1, 7])  # 브로드캐스팅된 결과 크기 출력

t23 = torch.ones(3, 3, 3)
t24 = torch.ones(3, 1, 3)
print((t23 + t24).size())  # torch.Size([3, 3, 3])  # 브로드캐스팅된 결과 크기 출력

# t25 = torch.empty(5, 2, 4, 1)
# t26 = torch.empty(3, 1, 1)
# print((t25 + t26).size())
# RuntimeError: The size of tensor a (2) must match
# the size of tensor b (3) at non-singleton dimension 1
# 브로드캐스팅을 위해서는 두 차원의 크기가 같거나 하나의 크기가 1이어야 하는데 아니라서 런타임 오류 발생

torch.Size([5, 3, 4, 1])
torch.Size([3, 1, 7])
torch.Size([3, 3, 3])


In [27]:
t27 = torch.ones(4) * 5
print(t27)  # >>> tensor([ 5, 5, 5, 5])  # 모든 요소가 5인 텐서

t28 = torch.pow(t27, 2)
print(t28)  # >>> tensor([ 25, 25, 25, 25])  # 각 요소를 제곱한 결과

exp = torch.arange(1., 5.)  # tensor([ 1.,  2.,  3.,  4.])
a = torch.arange(1., 5.)  # tensor([ 1.,  2.,  3.,  4.])
t29 = torch.pow(a, exp)
print(t29)  # >>> tensor([   1.,    4.,   27.,  256.])  # 각 요소를 지수로 제곱한 결과

tensor([5., 5., 5., 5.])
tensor([25., 25., 25., 25.])
tensor([  1.,   4.,  27., 256.])


텐서의 크기와 형태를 다루며, shape과 size 속성의 차이점에 대해 설명한다.
이러한 속성은 텐서 연산 및 모델 설계에서 중요한 역할을 하며, 특정 차원에 따라 연산이 어떻게 진행되는지를 이해하는 데 필요하다.
다양한 텐서의 차원을 조작하는 연습이 포함되어 있다.

# j_tensor_indexing_slicing.py

In [28]:
# 2D 텐서 생성
x = torch.tensor(
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9],
   [10, 11, 12, 13, 14]]
)

print(x[1])  # >>> tensor([5, 6, 7, 8, 9]) # 첫 번째 행 선택
print(x[:, 1])  # >>> tensor([1, 6, 11]) # 두 번째 열 선택
print(x[1, 2])  # >>> tensor(7) # 특정 요소 선택 (1행 2열)
print(x[:, -1])  # >>> tensor([4, 9, 14]) # 마지막 열 선택

tensor([5, 6, 7, 8, 9])
tensor([ 1,  6, 11])
tensor(7)
tensor([ 4,  9, 14])


In [29]:
print(x[1:])  # >>> tensor([[ 5,  6,  7,  8,  9], [10, 11, 12, 13, 14]]) # 1행부터 끝까지 선택
print(x[1:, 3:])  # >>> tensor([[ 8,  9], [13, 14]]) # 1행부터 끝까지, 3열부터 끝까지 선택

tensor([[ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])
tensor([[ 8,  9],
        [13, 14]])


In [30]:
y = torch.zeros((6, 6)) # 6x6 크기의 제로 텐서 생성
y[1:4, 2] = 1 # 1행부터 3행까지 2열에 1 할당
print(y)

print(y[1:4, 1:4]) # >>> tensor([[1., 1., 0.], [0., 0., 0.], [0., 0., 0.]]) # 1행부터 3행까지, 1열부터 3열까지 부분 선택

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])
tensor([[0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.]])


In [31]:
z = torch.tensor(
  [[1, 2, 3, 4],
   [2, 3, 4, 5],
   [5, 6, 7, 8]]
)

print(z[:2])  # >>> tensor([[1, 2, 3, 4], [2, 3, 4, 5]]) # 0행부터 1행까지 선택
print(z[1:, 1:3])  # >>> tensor([[3, 4], [6, 7]]) # 1행부터 끝까지, 1열부터 3열까지 선택
print(z[:, 1:])  # >>> tensor([[2, 3, 4], [3, 4, 5], [6, 7, 8]]) # 모든 행의 1열부터 끝까지 선택

z[1:, 1:3] = 0 # 1행부터 끝까지의 1열과 2열에 0 할당
print(z)  # 변경된 텐서 출력

tensor([[1, 2, 3, 4],
        [2, 3, 4, 5]])
tensor([[3, 4],
        [6, 7]])
tensor([[2, 3, 4],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[1, 2, 3, 4],
        [2, 0, 0, 5],
        [5, 0, 0, 8]])


텐서의 인덱싱과 슬라이싱을 통해 특정 원소에 접근하는 방법을 설명한다.
다양한 슬라이싱 기법을 통해 텐서에서 원하는 부분을 쉽게 추출할 수 있으며, 이 과정에서 복사본 생성 여부에 대한 주의가 필요하다.
인덱싱 기법은 모델의 특정 부분을 조작할 때 매우 유용하다.

# k_tensor_reshaping.py

In [32]:
t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
t2 = t1.view(3, 2)  # Shape becomes (3, 2), view는 메모리 재배치를 하지 않고 새로운 모양으로 반환
t3 = t1.reshape(1, 6)  # Shape becomes (1, 6), reshape은 유연하게 모양을 바꿔서 반환
print(t2)
print(t3)

t4 = torch.arange(8).view(2, 4)  # Shape becomes (2, 4), 연속된 값을 2x4로 보기
t5 = torch.arange(6).view(2, 3)  # Shape becomes (2, 3), 6개의 값을 2x3으로 변형
print(t4)
print(t5)

tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])
tensor([[0, 1, 2],
        [3, 4, 5]])


In [33]:
# Original tensor with shape (1, 3, 1)
t6 = torch.tensor([[[1], [2], [3]]])

# Remove all dimensions of size 1
t7 = t6.squeeze()  # Shape becomes (3,), 크기가 1인 차원 모두 제거
# Remove dimension at position 0
t8 = t6.squeeze(0)  # Shape becomes (3, 1), 첫 번째 차원 제거
print(t7)
print(t8)

tensor([1, 2, 3])
tensor([[1],
        [2],
        [3]])


In [34]:
# Original tensor with shape (3,)
t9 = torch.tensor([1, 2, 3])

# Add a new dimension at position 1
t10 = t9.unsqueeze(1)  # Shape becomes (3, 1), 두 번째 차원에 새로운 차원 추가
print(t10)

t11 = torch.tensor([[1, 2, 3], [4, 5, 6]])
t12 = t11.unsqueeze(1)  # Shape becomes (2, 1, 3), 첫 번째 차원에 새로운 차원 추가
print(t12, t12.shape)

tensor([[1],
        [2],
        [3]])
tensor([[[1, 2, 3]],

        [[4, 5, 6]]]) torch.Size([2, 1, 3])


In [35]:
# Original tensor with shape (2, 3)
t13 = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Flatten the tensor
t14 = t13.flatten()  # Shape becomes (6,), 모든 요소를 1차원으로 평탄화
print(t14)

# Original tensor with shape (2, 2, 2)
t15 = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
t16 = torch.flatten(t15)  # 모든 차원 평탄화
t17 = torch.flatten(t15, start_dim=1)  # 두 번째 차원부터 평탄화
print(t16)
print(t17)

tensor([1, 2, 3, 4, 5, 6])
tensor([1, 2, 3, 4, 5, 6, 7, 8])
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])


In [36]:
t18 = torch.randn(2, 3, 5)  # 무작위 텐서 생성, 모양은 (2, 3, 5)
print(t18.shape)  # >>> torch.Size([2, 3, 5])
print(torch.permute(t18, (2, 0, 1)).size())  # >>> torch.Size([5, 2, 3]), 차원 순서 변경

# Original tensor with shape (2, 3)
t19 = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Permute the dimensions
t20 = torch.permute(t19, dims=(0, 1))  # Shape becomes (2, 3), 동일한 차원 유지
t21 = torch.permute(t19, dims=(1, 0))  # Shape becomes (3, 2), 차원 순서 변경
print(t20)
print(t21)

# Transpose the tensor
t22 = torch.transpose(t19, 0, 1)  # Shape becomes (3, 2), 두 차원을 교환
print(t22)

t23 = torch.t(t19)  # Shape becomes (3, 2), 2차원 텐서 전치 (transpose와 동일)
print(t23)

torch.Size([2, 3, 5])
torch.Size([5, 2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])


여러 텐서를 연결(concatenate)하는 방법을 설명하며, 각 차원에서의 결합 방식을 다룬다.
연결 후 텐서의 차원 변화와 결과를 확인할 수 있으며, 모델의 입력 데이터 구성을 이해하는 데 도움이 된다.
concat 연산의 사용은 모델 구조 설계에서 중요한 요소로 작용한다.

# l_tensor_concat.py

In [37]:
t1 = torch.zeros([2, 1, 3])  
t2 = torch.zeros([2, 3, 3])  
t3 = torch.zeros([2, 2, 3])  

# 두 번째 차원(dim=1)이 다른 크기를 가질 수 있으며, 이 차원을 따라 합쳐짐.
t4 = torch.cat([t1, t2, t3], dim=1)  # 텐서의 모양을 (2, 6, 3)으로 변경
print(t4.shape)

torch.Size([2, 6, 3])


In [38]:
t5 = torch.arange(0, 3)  # tensor([0, 1, 2])
t6 = torch.arange(3, 8)  # tensor([3, 4, 5, 6, 7])

t7 = torch.cat((t5, t6), dim=0)  # 텐서의 모양을 (8,)로 변경
print(t7.shape)  
print(t7) 

torch.Size([8])
tensor([0, 1, 2, 3, 4, 5, 6, 7])


In [39]:
t8 = torch.arange(0, 6).reshape(2, 3)  # 텐서의 모양을 (2, 3)으로 변경
t9 = torch.arange(6, 12).reshape(2, 3)  # 텐서의 모양을 (2, 3)으로 변경

# 2차원 텐서간 병합
t10 = torch.cat((t8, t9), dim=0)  # 텐서의 모양을 (4, 3)으로 변경
print(t10.size())  
print(t10)

t11 = torch.cat((t8, t9), dim=1)  # 텐서의 모양을 (2, 6)으로 변경
print(t11.size())  
print(t11)

torch.Size([4, 3])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])
torch.Size([2, 6])
tensor([[ 0,  1,  2,  6,  7,  8],
        [ 3,  4,  5,  9, 10, 11]])


In [40]:
t12 = torch.arange(0, 6).reshape(2, 3)  # 텐서의 모양을 (2, 3)으로 변경
t13 = torch.arange(6, 12).reshape(2, 3)  # 텐서의 모양을 (2, 3)으로 변경
t14 = torch.arange(12, 18).reshape(2, 3)  # 텐서의 모양을 (2, 3)으로 변경

t15 = torch.cat((t12, t13, t14), dim=0)  # 텐서의 모양을 (6, 3)으로 변경
print(t15.size())  
print(t15)

t16 = torch.cat((t12, t13, t14), dim=1)  # 텐서의 모양을 (2, 9)로 변경
print(t16.size())  
print(t16)

torch.Size([6, 3])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]])
torch.Size([2, 9])
tensor([[ 0,  1,  2,  6,  7,  8, 12, 13, 14],
        [ 3,  4,  5,  9, 10, 11, 15, 16, 17]])


In [41]:
t17 = torch.arange(0, 6).reshape(1, 2, 3)  # 텐서의 모양을 (1, 2, 3)으로 변경
t18 = torch.arange(6, 12).reshape(1, 2, 3)  # 텐서의 모양을 (1, 2, 3)으로 변경

t19 = torch.cat((t17, t18), dim=0)  # 텐서의 모양을 (2, 2, 3)으로 변경
print(t19.size())  
print(t19)

t20 = torch.cat((t17, t18), dim=1)  # 텐서의 모양을 (1, 4, 3)으로 변경
print(t20.size())  
print(t20)

t21 = torch.cat((t17, t18), dim=2)  # 텐서의 모양을 (1, 2, 6)으로 변경
print(t21.size())  
print(t21)

torch.Size([2, 2, 3])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])
torch.Size([1, 4, 3])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]]])
torch.Size([1, 2, 6])
tensor([[[ 0,  1,  2,  6,  7,  8],
         [ 3,  4,  5,  9, 10, 11]]])


텐서의 형태를 변형(reshape)하는 방법을 다룬다.
reshape와 view 메소드를 통해 텐서의 차원을 조정하고, 이 과정에서 데이터의 연속성을 이해하는 것이 중요하다.
텐서의 형태를 조정하는 기술은 데이터 전처리 및 신경망 아키텍처 설계에서 필수적이다.

# m_tensor_stacking.py

In [42]:
t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
t2 = torch.tensor([[7, 8, 9], [10, 11, 12]])

# stack은 새로운 차원을 추가하여 텐서를 병합 (dim=0에서 2차원으로)
t3 = torch.stack([t1, t2], dim=0)  # 모양: (2, 2, 3)
# cat은 기존 차원에서 연결 (unsqueeze로 차원 추가 후 병합)
t4 = torch.cat([t1.unsqueeze(dim=0), t2.unsqueeze(dim=0)], dim=0)  # 모양: (2, 2, 3)
print(t3.shape, t3.equal(t4))

# dim=1에서 병합
t5 = torch.stack([t1, t2], dim=1)  # 모양: (2, 2, 3)
t6 = torch.cat([t1.unsqueeze(dim=1), t2.unsqueeze(dim=1)], dim=1)  # 모양: (2, 2, 3)
print(t5.shape, t5.equal(t6))

# dim=2에서 병합
t7 = torch.stack([t1, t2], dim=2)  # 모양: (2, 3, 2)
t8 = torch.cat([t1.unsqueeze(dim=2), t2.unsqueeze(dim=2)], dim=2)  # 모양: (2, 3, 2)
print(t7.shape, t7.equal(t8))

torch.Size([2, 2, 3]) True
torch.Size([2, 2, 3]) True
torch.Size([2, 3, 2]) True


In [43]:
# 1D 텐서 병합 (dim=0에서 병합)
t9 = torch.arange(0, 3)  # 모양: (3,)
t10 = torch.arange(3, 6)  # 모양: (3,)
t11 = torch.stack((t9, t10), dim=0)  # 모양: (2, 3)
t12 = torch.cat((t9.unsqueeze(0), t10.unsqueeze(0)), dim=0)  # 모양: (2, 3)
print(t11.equal(t12))  # True

# dim=1에서 병합
t13 = torch.stack((t9, t10), dim=1)  # 모양: (3, 2)
t14 = torch.cat((t9.unsqueeze(1), t10.unsqueeze(1)), dim=1)  # 모양: (3, 2)
print(t13.equal(t14))  # True

True
True


텐서의 전치(transpose)를 통해 차원의 순서를 변경하는 방법을 다룬다.
전치 연산은 행렬 연산에서 매우 중요하며, 특정 수학적 연산의 결과를 변경할 수 있다.
텐서의 전치 기술을 이해하는 것은 선형대수와 머신러닝 모델 설계에 필수적이다.

# n_tensor_vstack_hstack.py

In [44]:
t1 = torch.tensor([1, 2, 3])  # 1차원 텐서, shape은 (3,)
t2 = torch.tensor([4, 5, 6])  # 1차원 텐서, shape은 (3,)

# t1과 t2를 수직으로 쌓음 (dim=0을 따라), 결과적으로 (2, 3) 모양의 텐서 생성
t3 = torch.vstack((t1, t2))
print(t3)
# >>> tensor([[1, 2, 3],
#             [4, 5, 6]])

t4 = torch.tensor([[1], [2], [3]])  # 2차원 텐서, shape은 (3, 1)
t5 = torch.tensor([[4], [5], [6]])  # 2차원 텐서, shape은 (3, 1)

# t4와 t5를 수직으로 쌓음, 결과적으로 (6, 1) 모양의 텐서 생성
t6 = torch.vstack((t4, t5))
print(t6)
# >>> tensor([[1],
#             [2],
#             [3],
#             [4],
#             [5],
#             [6]])

# 3차원 텐서, shape은 (2, 2, 3)
t7 = torch.tensor([
  [[1, 2, 3], [4, 5, 6]],
  [[7, 8, 9], [10, 11, 12]]
])
print(t7.shape)
# >>> (2, 2, 3)

# 3차원 텐서, shape은 (2, 2, 3)
t8 = torch.tensor([
  [[13, 14, 15], [16, 17, 18]],
  [[19, 20, 21], [22, 23, 24]]
])
print(t8.shape)
# >>> (2, 2, 3)

# t7과 t8을 수직으로 쌓아 (4, 2, 3) 모양의 텐서 생성
t9 = torch.vstack([t7, t8])
print(t9.shape)
# >>> (4, 2, 3)

print(t9)
# >>> tensor([[[ 1,  2,  3],
#              [ 4,  5,  6]],
#             [[ 7,  8,  9],
#              [10, 11, 12]],
#             [[13, 14, 15],
#              [16, 17, 18]],
#             [[19, 20, 21],
#              [22, 23, 24]]])

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])
torch.Size([2, 2, 3])
torch.Size([2, 2, 3])
torch.Size([4, 2, 3])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]],

        [[13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24]]])


In [45]:
t10 = torch.tensor([1, 2, 3])  # 1차원 텐서, shape은 (3,)
t11 = torch.tensor([4, 5, 6])  # 1차원 텐서, shape은 (3,)

# t10과 t11을 수평으로 쌓아 (6,) 모양의 텐서 생성
t12 = torch.hstack((t10, t11))
print(t12)
# >>> tensor([1, 2, 3, 4, 5, 6])

t13 = torch.tensor([[1], [2], [3]])  # 2차원 텐서, shape은 (3, 1)
t14 = torch.tensor([[4], [5], [6]])  # 2차원 텐서, shape은 (3, 1)

# t13과 t14를 수평으로 쌓아 (3, 2) 모양의 텐서 생성
t15 = torch.hstack((t13, t14))
print(t15)
# >>> tensor([[1, 4],
#             [2, 5],
#             [3, 6]])

# 3차원 텐서, shape은 (2, 2, 3)
t16 = torch.tensor([
  [[1, 2, 3], [4, 5, 6]],
  [[7, 8, 9], [10, 11, 12]]
])
print(t16.shape)
# >>> (2, 2, 3)

# 3차원 텐서, shape은 (2, 2, 3)
t17 = torch.tensor([
  [[13, 14, 15], [16, 17, 18]],
  [[19, 20, 21], [22, 23, 24]]
])
print(t17.shape)
# >>> (2, 2, 3)

# t16과 t17을 수평으로 쌓아 (2, 4, 3) 모양의 텐서 생성
t18 = torch.hstack([t16, t17])
print(t18.shape)
# >>> (2, 4, 3)

print(t18)
# >>> tensor([[[ 1,  2,  3],
#              [ 4,  5,  6],
#              [13, 14, 15],
#              [16, 17, 18]],
#             [[ 7,  8,  9],
#              [10, 11, 12],
#              [19, 20, 21],
#              [22, 23, 24]]])

tensor([1, 2, 3, 4, 5, 6])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
torch.Size([2, 2, 3])
torch.Size([2, 2, 3])
torch.Size([2, 4, 3])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [13, 14, 15],
         [16, 17, 18]],

        [[ 7,  8,  9],
         [10, 11, 12],
         [19, 20, 21],
         [22, 23, 24]]])


브로드캐스팅 개념을 통해 서로 다른 크기의 텐서 간 연산을 수행하는 방법을 설명한다.
이 과정에서 각 텐서의 차원 맞춤을 자동으로 수행하여 효율적인 연산을 가능하게 한다.
브로드캐스팅 기술은 딥러닝에서 데이터의 형상에 따라 계산을 유연하게 처리하는 데 필수적이다.

# 숙제 후기

물론 수업때도 잘 알려주셨지만, 과제를 통해 실습을 함으로써 추가적으로 더 잘 이해가 되었고 기억에 남는 것 같습니다. 텐서는 기본적으로 다차원 배열을 의미하며, 데이터의 저장과 연산을 효율적으로 수행할 수 있도록 설계된 구조이고, 딥러닝 모델 학습에 용이하다는 것을 알게 되었습니다. 또한 텐서를 활용하기 위한 파이썬 문법들도 익히게 되었습니다.